title: LiuYing's Homepage
page-top-title: LiuYing
top-section-bg-text: Be what you wanna be
home-subtitle: WHPU & ensp;|&ensp;Computer Science and Technology
copyright-text: '&copy; LiuYing 2026. All Rights Reserved.'
